### ISSUE TITLE
NameError: name 'vim' is not defined

### ISSUE THREAD

**Issue by notno** [madox2/vim-ai#43]
I'm on ubuntu WSL and I installed python support with `apt install python3-neovim`

```
Error detected while processing function vim_ai#AIChatRun[30]..provider#python3#Call:
line   18:
Error invoking 'python_execute_file' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "/home/nrosquist/.local/share/nvim/lazy/vim-ai/py/chat.py", line 2, in <module>
    plugin_root = vim.eval("s:plugin_root")
NameError: name 'vim' is not defined
```

**Comment by madox2** [comment]
Hi, thanks for reporting! I think I fixed this issue by explicitly importing vim module. Please update the plugin and let me know if it works for you.

**Comment by notno** [comment]
Hmmm, that doesn't seem to fix it. 

I reinstalled the plugin via lazy, and double checked that your commit came through.

I wonder if it's something with my nvim python integration. I will see if I can test that separately

**Comment by madox2** [comment]
Closing due to inactivity

**Comment by madox2** [comment]
Closing due to inactivity

**Comment by AutoRescue** [comment]
`import vim` at the top of `~/.local/share/nvim/site/pack/plugins/start/vim-ai/py/complete.py` fixed this for me

**Comment by madox2** [comment]
@AutoRescue thank you for letting me know. I have pushed the fix, hope it definitely resolves this issue
